export const FALLBACK_VERSES = [
  { verse_reference: "Psalm 23:1", verse_text: "The Lord is my shepherd; I shall not want." },
  { verse_reference: "John 3:16", verse_text: "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life." },
  { verse_reference: "Philippians 4:13", verse_text: "I can do all things through him who strengthens me." },
  { verse_reference: "Proverbs 3:5-6", verse_text: "Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths." },
  { verse_reference: "Isaiah 40:31", verse_text: "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint." },
  { verse_reference: "Romans 8:28", verse_text: "And we know that for those who love God all things work together for good, for those who are called according to his purpose." },
  { verse_reference: "Joshua 1:9", verse_text: "Be strong and courageous. Do not be frightened, and do not be dismayed, for the Lord your God is with you wherever you go." },
  { verse_reference: "Jeremiah 29:11", verse_text: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope." },
  { verse_reference: "Matthew 11:28", verse_text: "Come to me, all who labor and are heavy laden, and I will give you rest." },
  { verse_reference: "Psalm 46:1", verse_text: "God is our refuge and strength, a very present help in trouble." },
  { verse_reference: "Galatians 5:22-23", verse_text: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law." },
  { verse_reference: "2 Corinthians 5:17", verse_text: "Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come." },
  { verse_reference: "Psalm 119:105", verse_text: "Your word is a lamp to my feet and a light to my path." },
  { verse_reference: "Romans 12:2", verse_text: "Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect." },
  { verse_reference: "Ephesians 2:8-9", verse_text: "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast." },
  { verse_reference: "John 14:6", verse_text: "Jesus said to him, I am the way, and the truth, and the life. No one comes to the Father except through me." },
  { verse_reference: "Psalm 27:1", verse_text: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?" },
  { verse_reference: "Lamentations 3:22-23", verse_text: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness." },
  { verse_reference: "1 Corinthians 13:4-5", verse_text: "Love is patient and kind; love does not envy or boast; it is not arrogant or rude. It does not insist on its own way; it is not irritable or resentful." },
  { verse_reference: "James 1:2-3", verse_text: "Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness." },
  { verse_reference: "Psalm 34:18", verse_text: "The Lord is near to the brokenhearted and saves the crushed in spirit." },
  { verse_reference: "Matthew 6:33", verse_text: "But seek first the kingdom of God and his righteousness, and all these things will be added to you." },
  { verse_reference: "Hebrews 11:1", verse_text: "Now faith is the assurance of things hoped for, the conviction of things not seen." },
  { verse_reference: "John 16:33", verse_text: "I have said these things to you, that in you you may have peace. In the world you will have tribulation. But take heart; I have overcome the world." },
  { verse_reference: "Psalm 103:2-3", verse_text: "Bless the Lord, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases." },
  { verse_reference: "2 Timothy 1:7", verse_text: "For God gave us a spirit not of fear but of power and love and self-control." },
  { verse_reference: "Philippians 4:6-7", verse_text: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus." },
  { verse_reference: "Psalm 37:4", verse_text: "Delight yourself in the Lord, and he will give you the desires of your heart." },
  { verse_reference: "Romans 5:8", verse_text: "But God shows his love for us in that while we were still sinners, Christ died for us." },
  { verse_reference: "1 Peter 5:7", verse_text: "Cast all your anxieties on him, because he cares for you." },
  { verse_reference: "Isaiah 41:10", verse_text: "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand." },
  { verse_reference: "Colossians 3:23", verse_text: "Whatever you do, work heartily, as for the Lord and not for men." },
  { verse_reference: "Psalm 91:1", verse_text: "He who dwells in the shelter of the Most High will abide in the shadow of the Almighty." },
  { verse_reference: "John 15:5", verse_text: "I am the vine; you are the branches. Whoever abides in me and I in him, he it is that bears much fruit, for apart from me you can do nothing." },
  { verse_reference: "Proverbs 31:25", verse_text: "Strength and dignity are her clothing, and she laughs at the time to come." },
  { verse_reference: "Romans 8:38-39", verse_text: "For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord." },
  { verse_reference: "Psalm 16:11", verse_text: "You make known to me the path of life; in your presence there is fullness of joy; at your right hand are pleasures forevermore." },
  { verse_reference: "Micah 6:8", verse_text: "He has told you, O man, what is good; and what does the Lord require of you but to do justice, and to love kindness, and to walk humbly with your God?" },
  { verse_reference: "Hebrews 4:16", verse_text: "Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need." },
  { verse_reference: "Psalm 145:18", verse_text: "The Lord is near to all who call on him, to all who call on him in truth." },
  { verse_reference: "Acts 1:8", verse_text: "But you will receive power when the Holy Spirit has come upon you, and you will be my witnesses in Jerusalem and in all Judea and Samaria, and to the end of the earth." },
  { verse_reference: "Matthew 5:8", verse_text: "Blessed are the pure in heart, for they shall see God." },
  { verse_reference: "Psalm 55:22", verse_text: "Cast your burden on the Lord, and he will sustain you; he will never permit the righteous to be moved." },
  { verse_reference: "Zephaniah 3:17", verse_text: "The Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing." },
  { verse_reference: "2 Chronicles 7:14", verse_text: "If my people who are called by my name humble themselves, and pray and seek my face and turn from their wicked ways, then I will hear from heaven and will forgive their sin and heal their land." },
  { verse_reference: "Psalm 139:14", verse_text: "I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well." },
  { verse_reference: "Mark 11:24", verse_text: "Therefore I tell you, whatever you ask in prayer, believe that you have received it, and it will be yours." },
  { verse_reference: "1 John 1:9", verse_text: "If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness." },
  { verse_reference: "Psalm 23:4", verse_text: "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me; your rod and your staff, they comfort me." },
  { verse_reference: "Matthew 28:19-20", verse_text: "Go therefore and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all that I have commanded you." },
  { verse_reference: "Revelation 21:4", verse_text: "He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away." },
  { verse_reference: "Psalm 1:1-2", verse_text: "Blessed is the man who walks not in the counsel of the wicked, nor stands in the way of sinners, nor sits in the seat of scoffers; but his delight is in the law of the Lord, and on his law he meditates day and night." },
] as const;

export function getDailyFallbackVerse() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - start.getTime()) / 86400000);
  return FALLBACK_VERSES[dayOfYear % FALLBACK_VERSES.length];
}
